### PR TITLE
Enable steady state and S-parameter analyses

### PR DESCRIPTION
**Pull request by sporrasm**
Goal is to add support for enabling steady state and S-parameter analyses, at least in Spectre.

- Frequency domain outputs should be put into iofile which has iotype='freq'
- Iotype 'freq' should be a column matrix, where the first column is frequency and the rest of the columns are (complex) magnitude
- S-parameters to self.extracts.Members['sparams']
- Simulator internal sweeping for pss?

@kspoof

### CODE REVIEW

**Comment by sporrasm** [comment]
@kspoof I tested pss with the following snippet (functionally the same your previous one, just changed some node names):

```
            _=spice_simcmd(self, sim='dc', plotlist=plotlist) #pss simcmd not yet done but spice needs a dummy simulation to run
            SR = 2*np.pi*self.fsig * 0.1
            ibias = SR * self.cload
            _=spice_dcsource(self, name='bias', pos='VDD', neg='IBIAS', value=ibias, sourcetype='I')
            self.spicemisc.append(f'VinD (VINP 0) port num=1 type=sine dc=0.45 ampl=0.1 freq={self.fsig} sinephase=0')
            self.spicemisc.append(f'Rfb (VINN VOUT) resistor r=0')
            self.spicemisc.append(f'PSS_analysis pss fund={self.fsig} outputtype=freq maxacfreq=20e9 harms=5')
            self.spicemisc.append(f'save VINP VOUT') #for now this defines saved outputs
            _=spice_iofile(self, name='out', dir='out', iotype='psfascii', ionames='VOUT')
            _=spice_iofile(self, name='in', dir='out', iotype='psfascii', ionames='VINP')
```

It seems to work. I took the liberty of transposing the output of psfutils so that the IOs are of same shape with other IO types (i.e. 'event', etc). See commit [0d97d66].(https://github.com/TheSystemDevelopmentKit/spice/pull/5/commits/0d97d667e4c4a71a37e3d8c9fd7ff760c545a6f7)
This is an excellent starting point, good work!

**Comment by kspoof** [comment]
@sporrasm port is missing some parameters that the normal pss analysis needs. At least ampl.

Spectre port has over 100 possible parameters, and different simulations need different params. I'm not sure if there are analyses where some parameters cannot be set simultaneously. Should this be changed so that there are no default params (or only those that are always needed), and instead only those parameters that are given are written for the port in the testbench? Even if there are no conflicts this would simplify debugging simulations. For example, now the port is always given 'mag' which doesn't do anything in a pss simulation, but you just have to know that.

Or then just use the spice_port only for the simplest cases and spicemisc otherwise.

**Comment by sporrasm** [comment]
> @sporrasm port is missing some parameters that the normal pss analysis needs. At least ampl.
> 
> Spectre port has over 100 possible parameters, and different simulations need different params. I'm not sure if there are analyses where some parameters cannot be set simultaneously. Should this be changed so that there are no default params (or only those that are always needed), and instead only those parameters that are given are written for the port in the testbench? Even if there are no conflicts this would simplify debugging simulations. For example, now the port is always given 'mag' which doesn't do anything in a pss simulation, but you just have to know that.
> 
> Or then just use the spice_port only for the simplest cases and spicemisc otherwise.

@kspoof. Sorry, I typed a reply to this last week but apparently forgot to post it.

I've noticed the same. I think small signal analyses (AC for example) use mag for specifying the magnitude. Large-signal analyses use other parameters (ampl, IIRC). And yes, since we probably do not want to debug possible conflicts with 100 different parameters and their different combinations, probably only the parameters that were given by the user should only be written for the in the testbench netlist. I do think that the spice_port implementation should support all analysis types that we implement (including pss). We just need to ensure that the use cases that *are* supported by the spice module are well documented. Of course, if this is a serious blocker, just use spicemisc and let's arrange a meeting to hammer this out at some point.

**Comment by kspoof** [comment]
@sporrasm I added 'psfascii' file reading for spectre sweeps. The output IO format (for each signal) is first column frequency and the one column for signal values from each sweep iteration.

Should be able to test like this:
```
self.pss_ampl=0.01
self.spiceparameters.update({'pss_ampl' : f'{self.pss_ampl}'})
self.spicemisc.append(f'VinD (VinD 0) port num=1 type=sine dc=0 ampl=pss_ampl freq={self.fsig} sinephase=0 mag=1')

self.sweep_param='pss_ampl'
self.sweep_values= np.linspace(1e-6,1e-1,num=10)

if self.sweep_param:
    tmpstr = np.array2string(self.sweep_values).replace('\n','')
    self.spicemisc.append(f'swp sweep param={self.sweep_param} values={tmpstr} {{')
self.spicemisc.append(f'PSS_analysis pss fund={self.fsig} outputtype=freq maxacfreq=20e9 harms=10')
if self.sweep_param:
    self.spicemisc.append(f'}}')
self.spicemisc.append(f'save VinD VoutD')
```

**Comment by kspoof** [comment]
For some reason when I was initially testing this 2 weeks ago, spectre always wrote a file PSS_analysis.fd.pss.
Now when I'm testing again this file doesn't show up. I haven't figured out what I'm doing differently.

Anyway, the current version is now working for me with the testbench code I gave earlier.

**Comment by sporrasm** [comment]
Hi @kspoof . Sorry, I've been a bit busy as of late but I managed to find some time to try this out finally. Looks good, I performed the test case you attached above. Harmonics seem to follow input power, so seems to work just fine. 

I'm guessing the simcmd should eventually be written for the PSS as well. I've enable the sweep type of simulation without the use of spicemisc in DC simulations on spectre in case you want to check an example. I would imagine that the PSS wouldn't be too much different.

In the mean time, I will try to finally add support for reading transient results with psf_utils. It would be interesting to see if this is faster than what we currently have.

**Comment by sporrasm** [comment]
It seems that reading in transient results with PSFutils seems to take considerably longer than with the current method. Do not know if this necessarily the way to go with transient. But, I probably for DC sweeps this is better than what is currently implemented.

**Comment by mkosunen** [comment]
@sporrasm @kspoof Is this still WIP? I'm about to release.

**Comment by sporrasm** [comment]
Yep, very much so, at least on my end.

**Pull request closed without merging**
