### PR TITLE
AC simulation

### PR DESCRIPTION
**Pull request by mkosunen**
@ojarvin @sporrasm @kspoof 

This is the branch for ac simulation development. I propose the following order

1. Implement simple AC simulation. I have an entity 'filter' for testing this, and I will push it to repo at some point once it simulates clean in some way. I will use 'spicemisc' property for sources for now.
2. Implement result parsing methodology. I think this should be at first place a general method that just assigns the result to some variable. We can decide later if we develop so kind of TheSyDeKick formalism for this, i.e. default property to which the result is assigned.

I think we should also refactor the simulation command string generation from testbench to spice_simcmd  to clarify the testbenh class, but that is a independent step. I will implement this ac stuff to testbench as it is structured now. 

If you have any insights you would like to share, let me know.

### CODE REVIEW

**Comment by mkosunen** [comment]
@ojarvin @sporrasm, @kspoof  I am done with the first version of AC simulation and event based IO handling for spectre.

However, first we need to check that the transients does not break (AC seems to work fine), so if you could run some trials with this.
### 
Intended/observed behaviour with 'event' type ios's: 

-  Iofile definition(s) results _all_ datapoints to be written in a single file in simulation run directory with the name tb_<name>.print. That file is then parsed to Data variables. File might be huge and it is parsed line by line as many times as you have different output files defined, so this may slow things down. If this beceomes a problem, we need to improve parsing.

- By giving spiceparameter `'printstep' 'yes'`  it is possible to force the fixed sampling interval to be used. Interval is defined with 'tstep' parameter given for transient simulation. This is demonstrated in the branch 'ac_devel_test' of inverter. Check that if you wish. I think this could be automated later on so that if tstep is given, 'printstep=yes' is also defined. However, it is not mandatory at the moment.

Please let me now if you find/do not find any problems.

I still need to clean up and publish the testcase for AC.

**Comment by mkosunen** [comment]
@ojarvin @sporrasm @kspoof 
AC can be tested with this
https://github.chttps://github.com/TheSystemDevelopmentKit/filterom/TheSystemDevelopmentKit/filter

**Comment by ojarvin** [comment]
Tested this briefly, and there is something wrong. All input signals are written to the same file `tb_*.print` according to stdout during initialization. Searching the database after simulation showed that all my event-type inputs have the same signal. I think the filename for the event inputs shouldn't be the same as for the outputs?

**Comment by mkosunen** [comment]
Oops. Should be fixed by b4d6155

**Comment by ojarvin** [comment]
This fixed it and the result looked fine.

There are still two places where the verilogA event writer is used: output signals with type 'time' and transient current used for power extraction. I think both of these could be replaced by the same print approach?

**Comment by mkosunen** [comment]
I think we can try to close this one now.  I assigned you three as erviewer, and if this seems to work, let's merge it to 1.6_RC.

We can further improve things in separate pull requests. Anyway, the main effor was to enable AC and not to break anything :)

**Pull request merged**
