### PR TITLE
Time stamped spectre

### PR DESCRIPTION
**Pull request by mkosunen**
@vlahtin This clutter removal is a proposal how the remove the extra timepoinsts. Should be baked in to read-in pahde of spectre results.

### CODE REVIEW

**Comment by vlahtin** [comment]
Tried to add it to the read in path (latest commit). Still having the same issues as with the original filter I implemented, where the filtering works for certain strobeperiods, but not for others. For example, this seems to work for me with 1e-12 strobing period with 1e-3 relerr for a 1GHz signal with 8GHz sampling frequency, but it doesn't work with e.g. 1e-13 strobing period for the same signal. It might be related to the relative error, but I couldn't figure out a relation between this and the behaviour and find a working solution. 

I think the issue with this filter is same as I had before, that theoretically it works, but as the numbers are so small (1e-12 to 1e-13), the floating point errors start to arise where Python has difficulties distinguishing the differences (atleast this is my hypothesis). I was thinking that one way would be just to read the IO file as a string, filter out the correct values as strings and after that read them into the vectors. 

If you have another idea or a reason on what is the cause of the "failed filtering" @mkosunen @sporrasm please suggest so I can try to solve this.

**Comment by vlahtin** [comment]
Added the file reading using pandas, which shortened the file reading time quite significantly. With 0.3GB simulation output file, the execution of read_spice_outputs dropped from 8.37s to 7.03s. 

Using an external sample clock IO for coherent sampling definetly is another bottleneck, as calling the interp_crossing function  of spice_iofile is called. Running the same simulation with sample clock to coherent sampling took  7.03s, while with strobeperiod and filtering it took under 0.968s. This is due to the interp_crossing running a for loop, which has to be run multiple times for every single sample point. So uniform sampling without the sampling clock is definetly sometihng that should be put more time looking into. 

The cause for the aforementioned sample issue is also found, it is due to the strobing period not returning exactly the correct values. It may return e.g.
` 2.560619999998e-07  5.986376835779e-01  5.982595828482e-01 -7.953917740041e-03 -2.388223935001e-10`
instead of just returning the timestamp of 2.5606200000e-07.  This results in the filter filtering out values that should be included but are not within the parameters. If the relerr is too small, these are filtered out, if it is too big unwanted data points get through.

**Comment by vlahtin** [comment]
The initial test for the latest filter seems to provide good speed while minimizing error. Will have to further test this with larger simulation files

**Comment by sporrasm** [comment]
MUY IMPORTANTE: Strobing and interactive_spice are mutually exclusive. Apparently the raw-database gets populated AFTER the simulation finishes, making interactive simulations impossible when strobing is enabled. Someone should probably investigate if it is possible to force spectre to write to file while simulation is running and when strobing is enabled. See #50.

**Comment by vlahtin** [comment]
Ran different tests with setting skipstarts and strobedelays, and even tried to set the strobetimesteps with a vector (https://community.cadence.com/cadence_blogs_8/b/cic/posts/spectre-tech-tips-using-the-spectre-strobe-feature). I even ran the simulations with exactly the same simulation commands given in the aforementioned link. Still the simulation outputs the garbage in between. 

I think this filtering is the way to go for now, and it works in my case atleast so it can be merged if wanted. Santeri's case is something that has to be investigated at some point

**Comment by sporrasm** [comment]
This cannot be merged in this state. My simulation crashed when reading in the simulator output:
18:06:09 [ERROR] spice_iofile: Traceback (most recent call last):
  File "$SDK_ROOT/Entities/spice/spice/spice_iofile.py", line 290, in parse_io_from_file
    encoding='utf-8',engine='c').to_numpy()[:-stop].astype(dtype)
  File "/home/pt/sporrasm/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/pt/sporrasm/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 460, in _read
    data = parser.read(nrows)
  File "/home/pt/sporrasm/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1198, in read
    ret = self._engine.read(nrows)
  File "/home/pt/sporrasm/.local/lib/python3.6/site-packages/pandas/io/parsers.py", line 2157, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 847, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 862, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 918, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 905, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 2042, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 6 fields in line 9673252, saw 10


18:06:09 [FATAL] spice_iofile: Failed while reading files for osc_start28.

Have to see what's up with this

**Comment by sporrasm** [comment]
Okay, now it doesn't crash anymore. However, I cannot verify whether or not this works, since my testbench had a save statement related to saving the sampling signal for sample type IO. Is it now so that I can run transient with event-type IOs as well as sample-type IOS? Are the sample type IOS parsed from output file based on strobeperiod? If so the corresponding parsing routine should be changed from spice_iofile.

**Comment by sporrasm** [comment]
Strobed outputs should go to event-based IO IF spice_iofile receives flag strobe=True.

**Comment by vlahtin** [comment]
The aforementioned functionality is now implemented where the strobed outputs go to event-based IO only if the flag is strobe=True. Currently this flag defaults to False.

Additional functionality is that you can now take multiple IOs of the same output node (e.g. OUTP).
`
            _=spice_iofile(self,name='OUTN',dir='out',iotype='event',sourcetype='V',
                    ionames='OUTN',strobe=True) 
            _=spice_iofile(self,name='OUTP',dir='out',iotype='event',sourcetype='V',
                    ionames='OUTP',strobe=True) 
            _=spice_iofile(self,name='OUTN_ns',dir='out',iotype='event',sourcetype='V',
                    ionames='OUTN',strobe=False) 
            _=spice_iofile(self,name='OUTP_ns',dir='out',iotype='event',sourcetype='V',
                    ionames='OUTP',strobe=False) 
`
In this example, OUTP and OUTN would be strobed, and OUTP_ns and OUTN_ns would take the same IO without strobing (consistent time stamps). This allows for time domain comparison of the same node to see how the strobed points match with the actual points. This is basically the functionality that the old method of having a sampling clock with sample IO.

This is working in my tests now, please test this as well. If it works for you I think this can now be merged

**Comment by sporrasm** [comment]
Seems to be working fine. Merge ok on my side.

**Pull request merged**
